### ISSUE TITLE
Integrate ocrd-skimage-*

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/ocrd-galley#33]
Needed for the recommended workflow: https://ocr-d.de/en/workflows#workflows

**Comment by cneud** [comment]
The module that provides the `ocrd_skimage-*` _[processors](https://ocr-d.de/en/spec/glossary#processor)_ you're presumabely refering to from the workflow guide is [ocrd_segment](https://github.com/OCR-D/ocrd_segment).

**Comment by mikegerber** [comment]
No, it's [ocrd_wrap](https://github.com/bertsky/ocrd_wrap/blob/master/ocrd_wrap/ocrd-tool.json)!

**Comment by mikegerber** [comment]
It's now in! 94a035e
