### ISSUE TITLE
Integrate ocrd-fileformat-*

### ISSUE THREAD

**Issue by cneud** [qurator-spk/ocrd-galley#34]
It would be very useful to include PAGE to ALTO transformation via [`ocrd-fileformat-transform`](https://ocr-d.de/en/workflows#step-19-format-conversion) from [ocrd_fileformat](https://github.com/OCR-D/ocrd_fileformat) in the workflow.

**Comment by mikegerber** [comment]
The latest update now has support for this, and we'll provide a way to set up custom workflow which could then use this.
