### ISSUE TITLE
Build stable Docker images using GitHub Actions

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/ocrd-galley#36]

**Comment by mikegerber** [comment]
After some fixes related to model downloads, the build seems to run along up to this useful error message with no lines available before that...

![image](https://user-images.githubusercontent.com/34309482/106934610-9a45ac00-671a-11eb-9e7a-9e2486736e02.png)


https://github.com/qurator-spk/ocrd-galley/runs/1832542708

**Comment by mikegerber** [comment]
After canceling the build, I got more info, it's related to ocrd-fileformat:
~~~
 make -C repo/ocr-fileformat PREFIX=/usr/local vendor install
make[1]: Entering directory '/data/ocrd_fileformat/repo/ocr-fileformat'
make -C vendor check
make[2]: Entering directory '/data/ocrd_fileformat/repo/ocr-fileformat/vendor'
make[2]: Leaving directory '/data/ocrd_fileformat/repo/ocr-fileformat/vendor'
# download the dependencies
make -C vendor all
make[2]: Entering directory '/data/ocrd_fileformat/repo/ocr-fileformat/vendor'
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
failed: Connection timed out.
Error: The operation was canceled.
~~~

**Comment by kba** [comment]
http://primaresearch.org/ has been down since yesterday, ocr-fileformat tries and fails to download the schemas from them.

Once they restore their web server this will work again. Since I think this is temporary, I'm hesitant to go through fixing ocr-fileformat and ocrd_fileformat now. If the problem remains though, let me know and I will.

**Comment by kba** [comment]
Since downtime might be longer than hoped, I've adapted ocr-fileformat and ocrd_fileformat to use the GitHub mirror of the schemas. Can you try with https://github.com/OCR-D/ocrd_fileformat/pull/28?

**Comment by mikegerber** [comment]
> Can you try with [OCR-D/ocrd_fileformat#28](https://github.com/OCR-D/ocrd_fileformat/pull/28)?

Trying out https://github.com/qurator-spk/ocrd-galley/commit/43cc303100d219dbdc4545fd94f5378d8430ef51 now!

**Comment by cneud** [comment]
Meanwhile https://www.primaresearch.org/ has come back online too.

**Comment by mikegerber** [comment]
[sighs]

**Comment by mikegerber** [comment]
After 40 minutes of waiting:
~~~
Successfully built d6a74002f537
Successfully tagged my_ocrd_workflow-ocrd_fileformat:latest
~~~

This is with OCR-D/ocrd_fileformat#28 still in place

**Comment by mikegerber** [comment]
Alright, giving up with building this with (free) online CI:

~~~
Step 8/13 : ADD data/mirror/github.com/tesseract-ocr/tessdata_best/archive/${TESSDATA_BEST_VERSION}-repacked.tar.gz $TESSDATA_PREFIX/
Error processing tar file(exit status 1): write /usr/local/share/tessdata/hrv.traineddata: no space left on device
Error: Process completed with exit code 1.
~~~
