### ISSUE TITLE
ppn2ocr: Rename BEST fileGrp to MAX

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/ocrd-galley#43]
As we are going to have a `MAX` fileGrp in the SBB's METS files, we are moving to `MAX` here too (instead of `BEST`). I am currently assuming that the SBB's `MAX` fileGrp is going to be made from `full` IIIF URLs, so identical to our current `BEST`.

@j23d @cneud 

- [ ] Rename BEST to MAX
- [ ] Handle an existing MAX

**Comment by kba** [comment]
:+1: for using `MAX`, I find it unexpected that this is renamed to `BEST`.

**Comment by mikegerber** [comment]
> +1 for using `MAX`, I find it unexpected that this is renamed to `BEST`.

It's not renamed, ppn2ocr *creates* this file group by guessing what the IIIF URL could be. I used `BEST` because it's the best images we can get by IIIF.

(Kitodo's MAX convention wasn't entirely clear to me because this file group rarely exists in the METS files I've seen)
