### ISSUE TITLE
WARNING ocrd_exif - ImageMagick 'identify' not available

### ISSUE THREAD

**Issue by mikegerber** [qurator-spk/ocrd-galley#60]
For example `ocrd-sbb-textline-detector --overwrite -I OCR-D-IMG-BIN -O OCR-D-SEG-LINE-SBB-TLD -P model "/var/lib/textline_detection` gives this warning:

```
16:42:12.171 WARNING ocrd_exif - ImageMagick 'identify' not available, Consider installing ImageMagick for more robust pixel density estimation
```

**Comment by kba** [comment]
This comes from OCR-D/core. The pixel density calculation of ImageMagick is more robust than PIL in my experience, hence we delegate to `identify` if it is available in `$PATH`. If it is not, we fall back to PIL to get the PPI.

**Comment by mikegerber** [comment]
Yeah, I thought so, I just need to include ImageMagick in the core images.
